import Navbar from "./../components/layout/Navbar/index";
import "./globals.css";
import Footer from "./../components/layout/Footer/index";

export const metadata = {
  title: "U!Source",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>
          <Navbar />
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
